updated

diff --git a/vi-theme b/vi-theme
--- a/vi-theme
+++ b/vi-theme
@@ -1,5 +1,6 @@
 #!/usr/bin/bash
 
+VIMPATH="$HOME/.vimrc"
 
 COUNT=1
 MAX=1
@@ -12,6 +13,7 @@ THEME="(@)(@)"
 TAB=8
 HIS_C=""
 SHOW="FALSE"
+
 
 # COLOR SCEAM
 G="\033[32m"
@@ -91,15 +93,23 @@ function option(){
 			if [ $opt -gt $(($MAX - 1)) ] 2>/dev/null;then invalied;break;fi
 			if [ $opt -lt 1 ] 2>/dev/null;then invalied; break;fi
 			if [ $COUNT -eq $opt ] 2>/dev/null;then
-				cat $HOME/.Theme-vim/Vim_color/colors/$i > $HOME/.vimrc   # Reset
-				printf "(${G}*${N}) THEME SUCESSFULLY APPLIED\n"
-				echo "set tabstop=$TAB" >> $HOME/.vimrc				# tabsize
-				echo "set shiftwidth=$(($TAB + 0))" >> $HOME/.vimrc # shiftwidth
+				cat $HOME/.Theme-vim/Vim_color/colors/$i > $VIMPATH  # Reset
+				echo "hi TabLine cterm=bold ctermfg=green ctermbg=236" >> $VIMPATH
+				echo "\"^ --- change non working tab color (236)" >> $VIMPATH
+				echo "hi TabLineFill ctermfg=234" >> $VIMPATH
+				echo "\"^ --- change non tab color (234)" >> $VIMPATH
+				echo "hi TabLineSel ctermfg=red" >> $VIMPATH
+				echo "\"^ -- change working tab color (red)" >> $VIMPATH
+				echo "hi CursorLineNr cterm=bold" >> $VIMPATH
+				echo "hi Error cterm=bold ctermfg=red ctermbg=none" >> $VIMPATH
+				printf "\n(${G}*${N}) THEME SUCESSFULLY APPLIED\n"
+				echo "set tabstop=$TAB" >> $VIMPATH                  # tabsize
+				echo "set shiftwidth=$(($TAB + 0))" >> $VIMPATH    # shiftwidth
 				printf "(${G}*${N}) TAB SIZE:${S}${TAB}${N}\n"
 				printf "(${G}*${N}) SHIFT WIDTH:${S}$((${TAB} + 0))${N}\n"
-				if [ $NUMBER = "TRUE" ];then printf "(${G}+${N}) INDUX ENABLED\n";echo "set number" >> $HOME/.vimrc;fi		# Nember set
-				if [ $LINE = "TRUE" ];then printf "(${G}+${N}) LINE ENABLED\n";echo "set cursorline" >> $HOME/.vimrc;fi		# Line set
-				if [ $COLUMN = "TRUE" ];then printf "(${G}+${N}) COLUMN ENABLED\n";echo "set cursorcolumn" >> $HOME/.vimrc;fi	# Column set
+				if [ $NUMBER = "TRUE" ];then printf "(${G}+${N}) INDUX ENABLED\n";echo "set number" >> $VIMPATH;fi		# Nember set
+				if [ $LINE = "TRUE" ];then printf "(${G}+${N}) LINE ENABLED\n";echo "set cursorline" >> $VIMPATH;fi		# Line set
+				if [ $COLUMN = "TRUE" ];then printf "(${G}+${N}) COLUMN ENABLED\n";echo "set cursorcolumn" >> $VIMPATH;fi	# Column set
 				echo "$i" >  $HOME/.Theme-vim/Vim_color/con/.his;
 				break
 			fi
@@ -113,42 +123,65 @@ function HELP_banner(){
 	printf "${R}Def${N}:
       vim Theme editing and debugging frame-work.
 ${R}Usage${N}:
-    ${NA}${ME} [-h] [-r=<value> --row=<value>]
-             [-l --line][-n --number][-c --column][-t=<value> --tab-size=<value>]
-             [-s --show][-a --add][-D --delete][-R --reset][-m --manual-edit]
+    ${NA}${ME} [-h] [-r=<value> --row=<value>][-l --line]
+             [-c --column][-t=<value> --tab-size=<value>]
+             [-s --show][-a --add][-D --delete][-R --reset]
+             [-m --manual-edit][-n --number][-A --about]
              [-d --debug -d=<filename> --debug=<filename>] \n
 
      ${P}ARGUMENT${N}                           ${P} DISCRIPTION${N}
      --------                            -----------
-        -a         --add               Add New vimrc file to database.
-                                       ${Y}EG${N}: ${NA}${ME} -a=test_file
-                                       or  ${NA}${ME} --add1=test2_file
         -c         --column            Enable Cursor column. (${Y}Vertical Line${N})
-        -d         --debug
-                   --debug=<filename>  Debug saved file.
-                                       ${Y}EG${N}: ${NA}${ME} -d=savedfile
-        -D         --delete=<fname>    Delete saved file.
-        -h         --help              Print Help banner.
         -l         --line              Enable Cursor line. (${Y}Horizontal Line${N})
-        -m         --manual-edit       Edit vimrc file manually.
         -n         --number            Enable Index number.
         -r         --row=<value>       Customize printing rows. (${Y}Default value${N}:4)
                                        Value must be Integer. 
                                        ${Y}EG${N}: ${NA}${ME} -r=3
-        -R         --reset             Reset vimrc to normal.
-        -s         --show              Show all the file and status.
         -t         --tab-size=<value>  Customize Tabsize vimrc. (${Y}Default value${N}:8)
                                        Value must be Integer.
-                                       ${Y}EG${N}: ${NA}${ME} -t=5
-        -A         --about             About.\n
+                                       ${Y}EG${N}: ${NA}${ME} -t=5\n
+   ${P}SOLO-ARGUMENT${N}
+    -----------
+        -a         --add               Add New vimrc file to database.
+                                       ${Y}EG${N}: ${NA}${ME} -a=test_file
+                                       or  ${NA}${ME} --add1=test2_file
+        -A         --about             About.
+        -C         --column-d          Dissable Cursor column. (${Y}Vertical Line${N})
+        -d         --debug
+                   --debug=<filename>  Debug saved file.
+                                       ${Y}EG${N}: ${NA}${ME} --debug=savedfile [-d]
+        -D         --delete=<fname>    Delete saved file.
+                                       ${Y}EG${N}: ${NA}${ME} -D=savedfile
+        -f         --file-type         Set default file type.
+        -h         --help              Print Help banner.
+        -L         --line-d            Dissable Cursor line. (${Y}Horizontal Line${N})
+        -m         --manual-edit       Edit vimrc file manually.
+        -N         --number-d          Dissable Index number.
+        -R         --reset             Reset vimrc to normal.
+        -s         --show              Show all the file and status.
+        -S         --show-vimrc        Print vimrc readable
+        -T         --tab-new           Enable New tab.
+        -TD        --tab-new-d         Dissable New tab.\n
 ${R}Example${N}:
-        ${UG}Normal vimrc edit${N}: ${NA}${ME} --row=3 --tab-size=4 --line --number    
-        ${UG}Debugmode${N}        : ${NA}${ME} --row=2 --debug \n
+
+        ${UG}Theme selection${N} : ${NA}${ME} --row=3 --tab-size=4 --line --number --column
+        ${UG}Debugmode${N}       : ${NA}${ME} --row=2 --debug 
+        ${UG}Add New file${N}    : ${NA}${ME} --add=Newfile
+        ${UG}Show status${N}     : ${NA}${ME} --show --row=3
+        ${UG}Manual edit${N}     : ${NA}${ME} --manual-edit
+        ${UG}Delete file${N}     : ${NA}${ME} --delete=Savedfile
+        ${UG}Reset vimrc${N}     : ${NA}${ME} --reset
+        ${UG}Dissable Line${N}   : ${NA}${ME} --line-d
+        ${UG}Dissable Number${N} : ${NA}${ME} --number-d
+        ${UG}Dissable Column${N} : ${NA}${ME} --column-d
+        ${UG}Enable New tab${N}  : ${NA}${ME} -T
+        ${UG}Dissable New tab${N}: ${NA}${ME} -TD\n
 ${R}INDICATION${N}: [ ${LS}#${N} Selected ] [ ${LG}#${N} Added ] [ ${P}#${N} Debugged ]\n"
 	for i in {16..21} {21..16} ; do printf "\e[38;5;${i}m${THEME}\e[0m";done;echo
 	exit 1
 }
 
+# Debug
 function Debug(){
 	update
 	LEN_CHECK
@@ -165,6 +198,35 @@ function Debug(){
 	done
 	exit 1
 }
+
+# File type
+function FILETYPE(){
+	list=(bash python vim html css java c cpp cs ruby)
+	c=1;if [ $ROW -gt 3 ];then ROW=3;fi
+	for i in $(seq 0 $((${#list[*]} - 1)));do
+		printf " ${R}%2s ${B}-${N} %-10s" "$COUNT" "${list[$i]}"
+		if [ $c -eq $ROW ] 2>/dev/null;then echo"";c=1;else c=$(($c + 1));fi
+		COUNT=$(($COUNT + 1))
+	done
+	printf "\n${S}OPTION${N}: "&read opt
+	COUNT=1
+	for i in $(seq 0 $((${#list[*]} - 1)));do
+		if [ $opt -eq $COUNT ] 2>/dev/null;then
+			cat $VIMPATH | grep setfiletype &>/dev/null
+			if [ $? -eq 0 ];then
+				cat $VIMPATH | sed 's/setfiletype/"setfiletype/' > .tmp
+				cat .tmp > $VIMPATH&&rm .tmp
+			fi
+			echo "setfiletype ${list[$i]}" >> $VIMPATH
+			printf "\n(${G}*${N}) DEFAULT FILE TYPE SET AS \"${G}${list[$i]}${N}\"\n"
+		fi
+		COUNT=$(($COUNT + 1))
+	done
+	exit 1
+}
+
+
+
 
 # ARGUMENTS
 #function Arguments(){
@@ -193,11 +255,11 @@ if true;then
 				for j in $(seq 1 100);do if [ $j -eq $TAB ] 2>/dev/null;then CHECK="TRUE";fi;done
 				if [ $CHECK = "FALSE" ];then printf "(${R}!${N}) Integer required,  ${NA}${ME} -t=<${G}int${N}>\n";exit 1;fi
 				if [ $TAB -lt 1 ];then TAB=1;fi
-				if [ $TAB -gt 50 ];then TAB=50;fi;;
-		
+				if [ $TAB -gt 50 ];then TAB=50;fi;;		
 			-t|--tab-size)
 				printf "${S}-t=${N}<value>  ${S}--tab-size=${N}<value> , value range (0 - ${Y}~${N}40)\n";exit 1;;
-
+			-S|--show-vimrc)
+				cat -b $VIMPATH 2>/dev/null;exit 1;;
 			-n|--number)
 				NUMBER="TRUE";;
 			-l|--line)
@@ -206,13 +268,10 @@ if true;then
 				COLUMN="TRUE";;
 			-h|--help)
 				HELP_banner;;
-
 			-m|--manual-edit)
-				vim $HOME/.vimrc;exit 1;;
-
+				vim $VIMPATH;exit 1;;
 			-R|--reset)
-				cd $HOME/.Theme-vim/Vim_color/con;printf "\"Reseted on ${R}$(date)${N}\n"  | tee $HOME/.vimrc && $(rm .his .his2 .his3 2>/dev/null); exit 1;;
-
+				cd $HOME/.Theme-vim/Vim_color/con;printf "\"Reseted on ${R}$(date)${N}\n"  | tee $VIMPATH && $(rm .his .his2 .his3 2>/dev/null); exit 1;;
 			-a=*|--add=*)
 				FILE="${i##*\=}"
 				if [ $FILE = $No_given ] 2>/dev/null;then printf "${S}-a=${N}<filename>  ${S}--add=${N}<filename>.\n";exit 1;fi
@@ -227,13 +286,11 @@ if true;then
 					printf "(${G}*${N}) FILENAME: ${FILE}\n";
 				else
 					printf "(${R}!${N}) ${R}${FILE}${N} NOT FOUND.\n"
-				fi;exit 1;;
-		
+				fi;exit 1;;		
 			-a|--add)
 				printf "${S}-a=${N}<filename>  ${S}--add=${N}<filename>.\n";exit 1;;
 			-A|--about)
 				Author && exit 1;;
-
 			-d=*|--debug=*)
 				FILE="${i##*\=}"
 				if [ $FILE = $No_given ] 2>/dev/null;then printf "${S}-d=${N}<filename>  ${S}--debug=${N}<filename>.\n";exit 1;fi
@@ -245,7 +302,8 @@ if true;then
 				fi;exit 1;;
 			-d|--debug)
 				DEBUG="TRUE";;
-
+			-f|--file-type)
+				FILETYPE;;
 			-D=*|--delete=*)
 				FILE="${i##*\=}"
 				if [ $FILE = $No_given ] 2>/dev/null;then printf "${S}-D=${N}<filename>  ${S}--delete=${N}<filename>.\n";exit 1;fi
@@ -258,8 +316,56 @@ if true;then
 				fi;exit 1;;
 			-s|--show)
 				SHOW="TRUE";;
-				#update;LEN_CHECK;display;echo "";exit 2;;
-		
+			-L|--line-d)
+				cat $VIMPATH | grep 'set cursorline' &>/dev/null
+				if [ $? -eq 0 ];then
+					cat $VIMPATH | sed 's/set cursorline//' > .tmp
+					cat .tmp > $VIMPATH&rm .tmp
+					printf "(${G}-${N}) SUCESSFULLY DISSABLED.\n"
+				else
+					printf "(${G}*${N}) ALREADY SATISFIED.\n"
+				fi
+				exit 1;;
+			-N|--number-d)
+				cat $VIMPATH | grep 'set number' &>/dev/null
+				if [ $? -eq 0 ];then
+					cat $VIMPATH | sed 's/set number//' > .tmp
+					cat .tmp > $VIMPATH&rm .tmp
+					printf "(${G}-${N}) SUCESSFULLY DISSABLED.\n"
+				else
+					printf "(${G}*${N}) ALREADY SATISFIED.\n"
+				fi;exit 1;;
+			-C|--column-d)
+				cat $VIMPATH | grep 'set cursorcolumn' &>/dev/null
+				if [ $? -eq 0 ];then
+					cat $VIMPATH | sed 's/set cursorcolumn//' > .tmp
+					cat .tmp > $VIMPATH&rm .tmp
+					printf "(${G}-${N}) SUCESSFULLY DISSABLED.\n"
+				else
+					printf "(${G}*${N}) ALREADY SATISFIED.\n"
+				fi;exit 1;;
+			-TD|--tab-new-d)
+				cat $VIMPATH | grep 'tabnew' &>/dev/null
+				if [ $? -eq 0 ];then
+					cat $VIMPATH | sed 's/tabnew//' > .tmp
+					cat .tmp > $VIMPATH&rm .tmp
+					cat $VIMPATH | sed 's/tabnext//' > .tmp
+					cat .tmp > $VIMPATH&rm .tmp
+					printf "(${G}-${N}) SUCESSFULLY DISSABLED.\n"
+				else
+					printf "(${G}*${N}) ALREADY SATISFIED.\n"
+				fi;exit 1;;
+				
+			-T|--tab-new)
+				cat $VIMPATH | grep 'tabnew' &>/dev/null
+				if [ $? -eq 0 ];then
+					printf "(${G}*${N}) ALREADY SATISFIED.\n"
+					exit 1
+				else
+					echo "tabnew" >> $VIMPATH
+					echo "tabnext" >> $VIMPATH
+					printf "(${G}+${N}) SUCESSFULLY ENNABLED.\n(${G}*${N}) If you want to edit manually use \'-m\'.\n"
+				fi;exit 1;;
 			-D|--delete)
 				printf "${S}-D=${N}<filename>  ${S}--delete=${N}<filename>.\n";exit 1;;
 
@@ -288,7 +394,7 @@ BANNER
 SETUP
 update
 LEN_CHECK
-display
 if [ $DEBUG = "TRUE" ] 2>/dev/null;then Debug;exit 1;fi
+display
 if [ $SHOW = "FALSE" ] 2>/dev/null;then option;fi
 echo ""
